# Read The Docs config
# - https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

sphinx:
  builder: html
  configuration: readthedocs/conf.py
  fail_on_warning: false

# python version
python:
    version: 3.5
    install:
        - requirements: readthedocs/requirements.txt
        - method: pip
   
# Just the HTML and indexing
formats: []

